# Generated by Django 4.0.6 on 2022-07-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointments_is_free'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patients',
            unique_together={('name', 'phone_number')},
        ),
    ]
