# Generated by Django 4.0.6 on 2022-07-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_patients_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
