# Generated by Django 4.0.6 on 2022-07-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_patients_phone_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patients',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name='patients',
            constraint=models.UniqueConstraint(fields=('name', 'phone_number'), name='appointments_patients_unique'),
        ),
    ]
