# Generated by Django 4.0.6 on 2022-07-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_patients_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patients',
            name='appointments_patients_unique',
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
