# Generated by Django 4.0.6 on 2022-07-26 14:10

import appointments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_alter_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[appointments.validators.validate_phone]),
        ),
    ]
