# Generated by Django 4.0.6 on 2022-07-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_appointment_hour_appointment_minute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='minute',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='month',
            field=models.IntegerField(),
        ),
    ]
