# Generated by Django 4.0.6 on 2022-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_alter_appointment_name_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
