# Generated by Django 4.0.6 on 2022-08-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0039_remove_appointment_date_time_appointment_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='minute',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='year',
            field=models.IntegerField(),
        ),
    ]
