# Generated by Django 4.1 on 2022-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0045_alter_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='anemia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_sugar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='bmi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='heart_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='kidney_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='liver_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='other_problems',
            field=models.TextField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='thyroid_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], default=17),
        ),
    ]
