# Generated by Django 4.1 on 2022-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0046_appointment_payment_patient_anemia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
