# Generated by Django 4.0.6 on 2022-07-23 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_patients_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='date',
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointments.patients'),
        ),
    ]
