# Generated by Django 4.0.6 on 2022-07-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointments_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patients',
            unique_together={('id', 'name', 'phone_number')},
        ),
    ]
