# Generated by Django 4.0.6 on 2022-07-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment',
            new_name='Appointments',
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
    ]
