# Generated by Django 4.0.6 on 2022-07-25 19:09

import appointments.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[appointments.validators.validate_age]),
        ),
    ]
