# Generated by Django 4.0.6 on 2022-07-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_alter_appointment_day_alter_appointment_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
