# Generated by Django 4.0.6 on 2022-08-04 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0035_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='minute',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='year',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 20, 43, 4, 741558)),
        ),
    ]
