# Generated by Django 4.0.6 on 2022-08-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0037_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='date_time',
        ),
    ]
