# Generated by Django 4.1 on 2022-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0044_alter_appointment_day_alter_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Respiratory System', 'Respiratory System'), ('Bones and Joints', 'Bones and Joints'), ('Heart and Blood Vessels', 'Heart and Blood Vessels'), ('Female Problems', 'Female Problems'), ('Urinary System', 'Urinary System'), ('Nerves and Muscles', 'Nerves and Muscles'), ('Immunity and Blood Booster', 'Immunity and Blood Booster'), ('Hormones', 'Hormones'), ('Other', 'Other')], max_length=64, null=True),
        ),
    ]
