# Generated by Django 4.1 on 2022-08-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0047_alter_patient_bmi_alter_patient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bmi',
            field=models.FloatField(blank=True),
        ),
    ]
